name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  post_release:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.14.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
