name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  post-release:
    name: Post Release Actions
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Run Changeset and Git Commands
        run: pnpm run changeset-and-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
